// CampusAnon — Dark Mysterious Neon Design System
// Aesthetic: Deep space terminal meets luxury dating app

export const theme = {
  bg: '#080810',
  bgCard: '#0d0d1a',
  bgHover: '#12122a',
  bgSurface: '#111128',
  border: '#1e1e3f',
  neon: '#ff2d78',
  neonDim: 'rgba(255,45,120,0.15)',
  neonGlow: '0 0 20px rgba(255,45,120,0.4), 0 0 40px rgba(255,45,120,0.1)',
  neonGlowSm: '0 0 10px rgba(255,45,120,0.3)',
  cyan: '#00f5ff',
  cyanDim: 'rgba(0,245,255,0.1)',
  text: '#e8e8ff',
  textMuted: '#6666aa',
  textDim: '#3a3a6a',
  success: '#00ff88',
  error: '#ff4466',
  gradient: 'linear-gradient(135deg, #ff2d78, #ff6b35)',
};

const mono = "'Share Tech Mono', 'Courier New', monospace";
const sans = "'DM Sans', 'Segoe UI', sans-serif";

export const styles = {
  appWrap: {
    display: 'flex', flexDirection: 'column', minHeight: '100vh',
    fontFamily: sans, background: theme.bg, color: theme.text,
    backgroundImage: `radial-gradient(ellipse at 20% 50%, rgba(255,45,120,0.03) 0%, transparent 60%),
                      radial-gradient(ellipse at 80% 20%, rgba(0,245,255,0.03) 0%, transparent 60%)`,
  },
  body: { display: 'flex', flex: 1 },
  main: { flex: 1, overflow: 'auto' },
  loadingWrap: {
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    height: '80vh', fontSize: 16, color: theme.textMuted, fontFamily: mono, letterSpacing: 2,
  },
  header: {
    display: 'flex', alignItems: 'center', padding: '0 28px', height: 58,
    background: 'rgba(8,8,16,0.95)', backdropFilter: 'blur(20px)',
    borderBottom: `1px solid ${theme.border}`,
    position: 'sticky', top: 0, zIndex: 100,
    boxShadow: '0 1px 0 rgba(255,45,120,0.1)',
  },
  headerLogo: {
    fontSize: 18, fontWeight: 700, cursor: 'pointer', marginRight: 'auto',
    fontFamily: mono, color: theme.text, letterSpacing: 1,
    display: 'flex', alignItems: 'center', gap: 8,
  },
  headerNav: { display: 'flex', gap: 2 },
  navBtn: {
    background: 'none', border: 'none', borderRadius: 6, padding: '6px 14px',
    cursor: 'pointer', fontSize: 13, color: theme.textMuted, fontFamily: sans, transition: 'all 0.2s',
  },
  navBtnActive: { color: theme.neon, background: theme.neonDim },
  headerRight: { display: 'flex', alignItems: 'center', gap: 12, marginLeft: 20 },
  aliasTag: {
    background: theme.neonDim, border: `1px solid rgba(255,45,120,0.3)`,
    padding: '4px 12px', borderRadius: 20, fontSize: 12,
    color: theme.neon, fontFamily: mono, letterSpacing: 1,
  },
  logoutBtn: {
    background: 'none', border: `1px solid ${theme.border}`, borderRadius: 6,
    padding: '5px 12px', cursor: 'pointer', fontSize: 12,
    color: theme.textMuted, fontFamily: sans, transition: 'all 0.2s',
  },
  sidebar: {
    width: 220, background: theme.bgCard, borderRight: `1px solid ${theme.border}`,
    padding: '24px 12px', display: 'flex', flexDirection: 'column', gap: 2, flexShrink: 0,
  },
  sidebarUser: { display: 'flex', alignItems: 'center', gap: 12, padding: '4px 8px 20px', marginBottom: 4 },
  sidebarAvatar: {
    width: 42, height: 42, borderRadius: '50%', background: theme.gradient, color: '#fff',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 18, fontWeight: 700, fontFamily: mono, boxShadow: theme.neonGlowSm, flexShrink: 0,
  },
  sidebarAlias: { fontWeight: 600, fontSize: 13, color: theme.text, fontFamily: mono },
  sidebarGender: { color: theme.textMuted, fontSize: 11, marginTop: 2 },
  sidebarDivider: { border: 'none', borderTop: `1px solid ${theme.border}`, margin: '10px 0' },
  sidebarItem: {
    display: 'flex', alignItems: 'center', gap: 10, padding: '10px 14px', borderRadius: 8,
    border: 'none', background: 'none', cursor: 'pointer', fontSize: 13,
    textAlign: 'left', color: theme.textMuted, width: '100%', fontFamily: sans, transition: 'all 0.15s',
  },
  sidebarItemActive: { background: theme.neonDim, color: theme.neon, borderLeft: `2px solid ${theme.neon}` },
  sidebarStats: { display: 'flex', gap: 6, marginTop: 8 },
  statBox: {
    flex: 1, textAlign: 'center', background: theme.bgSurface, borderRadius: 8,
    padding: '10px 4px', display: 'flex', flexDirection: 'column', gap: 3,
    fontSize: 11, border: `1px solid ${theme.border}`, color: theme.textMuted,
  },
  authWrap: {
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    flex: 1, padding: 24, minHeight: '85vh',
    background: 'linear-gradient(180deg, #080810 0%, #0a0820 100%)',
  },
  authCard: {
    background: theme.bgCard, border: `1px solid ${theme.border}`, borderRadius: 16,
    padding: '44px 40px', width: '100%', maxWidth: 420,
    boxShadow: `0 0 0 1px rgba(255,45,120,0.05), 0 24px 80px rgba(0,0,0,0.6)`,
  },
  authTitle: {
    fontSize: 26, fontWeight: 700, textAlign: 'center', marginBottom: 6,
    fontFamily: mono, color: theme.text, letterSpacing: 1,
  },
  authSubtitle: { color: theme.textMuted, textAlign: 'center', marginBottom: 28, fontSize: 13, lineHeight: 1.5 },
  infoBox: {
    background: 'rgba(0,255,136,0.08)', border: '1px solid rgba(0,255,136,0.2)',
    borderRadius: 8, padding: '12px 16px', marginBottom: 16, fontSize: 13, color: theme.success, lineHeight: 1.5,
  },
  input: {
    display: 'block', width: '100%', padding: '11px 14px', marginBottom: 12,
    border: `1px solid ${theme.border}`, borderRadius: 8, fontSize: 14,
    boxSizing: 'border-box', fontFamily: sans,
    background: theme.bgSurface, color: theme.text, outline: 'none', transition: 'border-color 0.2s',
  },
  label: {
    display: 'block', fontWeight: 600, fontSize: 12, marginBottom: 8,
    color: theme.textMuted, letterSpacing: 1, textTransform: 'uppercase',
  },
  genderRow: { display: 'flex', gap: 8, marginBottom: 16 },
  genderBtn: {
    flex: 1, padding: '9px 4px', border: `1px solid ${theme.border}`, borderRadius: 8,
    background: theme.bgSurface, cursor: 'pointer', fontSize: 12,
    fontFamily: sans, color: theme.textMuted, transition: 'all 0.15s',
  },
  genderBtnActive: {
    background: theme.neonDim, color: theme.neon,
    border: `1px solid rgba(255,45,120,0.4)`, boxShadow: theme.neonGlowSm,
  },
  primaryBtn: {
    display: 'block', width: '100%', padding: '12px', background: theme.gradient,
    color: '#fff', border: 'none', borderRadius: 8, cursor: 'pointer', fontSize: 14,
    fontWeight: 700, marginTop: 8, textAlign: 'center', fontFamily: sans,
    letterSpacing: 0.5, transition: 'opacity 0.2s', boxShadow: theme.neonGlowSm,
  },
  secondaryBtn: {
    display: 'block', padding: '9px 16px', background: 'none', color: theme.textMuted,
    border: `1px solid ${theme.border}`, borderRadius: 8, cursor: 'pointer',
    fontSize: 13, marginTop: 6, fontFamily: sans, transition: 'all 0.15s',
  },
  authSwitch: { textAlign: 'center', marginTop: 18, fontSize: 13, color: theme.textMuted },
  authLink: { color: theme.neon, fontWeight: 600, cursor: 'pointer' },
  error: { color: theme.error, fontSize: 12, marginBottom: 8 },
  page: { padding: '36px 44px', maxWidth: 960 },
  pageTitle: { fontSize: 28, fontWeight: 700, marginBottom: 6, fontFamily: mono, color: theme.text, letterSpacing: 0.5 },
  pageSubtitle: { color: theme.textMuted, marginBottom: 32, fontSize: 14 },
  emptyState: { textAlign: 'center', padding: '80px 20px', color: theme.textMuted },
  matchBanner: {
    background: `linear-gradient(135deg, rgba(255,45,120,0.15), rgba(255,107,53,0.1))`,
    border: `1px solid rgba(255,45,120,0.3)`, color: theme.neon,
    padding: '14px 20px', borderRadius: 10, marginBottom: 24, textAlign: 'center',
    fontWeight: 700, fontSize: 15, boxShadow: theme.neonGlowSm, fontFamily: mono,
  },
  discoverWrap: { display: 'flex', flexDirection: 'column', alignItems: 'center', paddingTop: 8 },
  profileCard: {
    background: theme.bgCard, border: `1px solid ${theme.border}`, borderRadius: 20,
    padding: '40px 36px', width: 360, textAlign: 'center',
    transition: 'transform 0.4s ease, opacity 0.4s ease',
    boxShadow: '0 20px 60px rgba(0,0,0,0.5)', position: 'relative', overflow: 'hidden',
  },
  profileAvatar: {
    width: 88, height: 88, borderRadius: '50%', background: theme.gradient, color: '#fff',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 38, fontWeight: 700, margin: '0 auto 16px', fontFamily: mono, boxShadow: theme.neonGlow,
  },
  profileAlias: { fontSize: 22, fontWeight: 700, marginBottom: 6, fontFamily: mono, color: theme.text, letterSpacing: 1 },
  profileMeta: { color: theme.textMuted, fontSize: 13, marginBottom: 10 },
  profileBio: {
    color: theme.textMuted, fontSize: 13, fontStyle: 'italic', marginBottom: 16, lineHeight: 1.6,
    borderLeft: `2px solid rgba(255,45,120,0.3)`, paddingLeft: 12, textAlign: 'left',
  },
  cardLiked: { transform: 'translateX(100px) rotate(12deg)', opacity: 0 },
  cardPassed: { transform: 'translateX(-100px) rotate(-12deg)', opacity: 0 },
  interestRow: { display: 'flex', flexWrap: 'wrap', gap: 6, justifyContent: 'center', marginBottom: 24 },
  interestTag: {
    background: theme.cyanDim, border: `1px solid rgba(0,245,255,0.2)`, borderRadius: 20,
    padding: '4px 12px', fontSize: 11, color: theme.cyan, fontFamily: mono, letterSpacing: 0.5,
  },
  interestTagSm: {
    background: theme.cyanDim, borderRadius: 20, padding: '3px 8px',
    fontSize: 10, color: theme.cyan, fontFamily: mono,
  },
  actionRow: { display: 'flex', gap: 16, justifyContent: 'center' },
  passBtn: {
    padding: '12px 32px', background: 'none', border: `1px solid rgba(255,68,102,0.4)`,
    color: '#ff4466', borderRadius: 30, cursor: 'pointer', fontSize: 14,
    fontWeight: 700, fontFamily: sans, transition: 'all 0.2s',
  },
  likeBtn: {
    padding: '12px 32px', background: theme.gradient, color: '#fff',
    border: 'none', borderRadius: 30, cursor: 'pointer', fontSize: 14,
    fontWeight: 700, fontFamily: sans, boxShadow: theme.neonGlowSm,
  },
  cardCounter: { marginTop: 20, color: theme.textDim, fontSize: 12, fontFamily: mono, letterSpacing: 1 },
  matchGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(230px, 1fr))', gap: 20 },
  matchCard: {
    background: theme.bgCard, border: `1px solid ${theme.border}`, borderRadius: 16,
    padding: 24, textAlign: 'center', transition: 'border-color 0.2s',
    position: 'relative', overflow: 'hidden',
  },
  matchAvatar: {
    width: 64, height: 64, borderRadius: '50%', background: theme.gradient, color: '#fff',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 26, fontWeight: 700, margin: '0 auto 12px', fontFamily: mono, boxShadow: theme.neonGlowSm,
  },
  matchAlias: { fontWeight: 700, fontSize: 16, marginBottom: 4, fontFamily: mono, color: theme.text },
  matchMeta: { color: theme.textMuted, fontSize: 12, marginBottom: 12 },
  chatLayout: { display: 'flex', height: 'calc(100vh - 58px)' },
  chatList: { width: 268, background: theme.bgCard, borderRight: `1px solid ${theme.border}`, overflowY: 'auto', flexShrink: 0 },
  chatListTitle: {
    padding: '18px 16px 12px', fontWeight: 700, fontSize: 11, letterSpacing: 2,
    textTransform: 'uppercase', color: theme.textMuted, fontFamily: mono,
    borderBottom: `1px solid ${theme.border}`,
  },
  chatListItem: {
    display: 'flex', alignItems: 'center', gap: 10, padding: '12px 16px',
    cursor: 'pointer', borderBottom: `1px solid rgba(30,30,63,0.5)`,
    position: 'relative', transition: 'background 0.15s',
  },
  chatListItemActive: { background: theme.bgHover, borderLeft: `2px solid ${theme.neon}` },
  chatListAvatar: {
    width: 40, height: 40, borderRadius: '50%', background: theme.gradient, color: '#fff',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 16, fontWeight: 700, flexShrink: 0, fontFamily: mono,
  },
  chatListName: { fontWeight: 600, fontSize: 13, color: theme.text, fontFamily: mono },
  chatListPreview: { color: theme.textMuted, fontSize: 11, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  onlineDot: {
    width: 8, height: 8, borderRadius: '50%', background: theme.success,
    position: 'absolute', right: 14, top: 14, boxShadow: '0 0 6px rgba(0,255,136,0.6)',
  },
  chatWindow: { flex: 1, display: 'flex', flexDirection: 'column', background: theme.bg },
  chatHeader: {
    display: 'flex', alignItems: 'center', gap: 12, padding: '14px 24px',
    borderBottom: `1px solid ${theme.border}`, background: theme.bgCard, flexShrink: 0,
  },
  chatHeaderAvatar: {
    width: 38, height: 38, borderRadius: '50%', background: theme.gradient, color: '#fff',
    display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 16, fontWeight: 700, fontFamily: mono,
  },
  chatHeaderName: { fontWeight: 700, fontSize: 15, fontFamily: mono, color: theme.text },
  chatHeaderStatus: { fontSize: 11, color: theme.textMuted },
  messagesArea: { flex: 1, overflowY: 'auto', padding: '24px', display: 'flex', flexDirection: 'column', gap: 10 },
  msgWrapMe: { display: 'flex', flexDirection: 'column', alignItems: 'flex-end' },
  msgWrapThem: { display: 'flex', flexDirection: 'column', alignItems: 'flex-start' },
  msgBubbleMe: {
    background: theme.gradient, color: '#fff', borderRadius: '18px 18px 4px 18px',
    padding: '10px 16px', maxWidth: 300, fontSize: 14, lineHeight: 1.5, boxShadow: theme.neonGlowSm,
  },
  msgBubbleThem: {
    background: theme.bgCard, border: `1px solid ${theme.border}`,
    borderRadius: '18px 18px 18px 4px', padding: '10px 16px',
    maxWidth: 300, fontSize: 14, color: theme.text, lineHeight: 1.5,
  },
  msgTime: { fontSize: 10, color: theme.textDim, marginTop: 3, fontFamily: mono },
  chatInputRow: {
    display: 'flex', gap: 10, padding: '14px 20px',
    borderTop: `1px solid ${theme.border}`, background: theme.bgCard, flexShrink: 0,
  },
  chatInput: {
    flex: 1, padding: '10px 16px', border: `1px solid ${theme.border}`, borderRadius: 24,
    fontSize: 14, outline: 'none', fontFamily: sans, background: theme.bgSurface, color: theme.text,
  },
  sendBtn: {
    padding: '10px 20px', background: theme.gradient, color: '#fff', border: 'none',
    borderRadius: 24, cursor: 'pointer', fontWeight: 700, fontFamily: sans, fontSize: 13, boxShadow: theme.neonGlowSm,
  },
  profileEditCard: {
    background: theme.bgCard, border: `1px solid ${theme.border}`, borderRadius: 16,
    padding: 36, maxWidth: 520, boxShadow: '0 20px 60px rgba(0,0,0,0.4)',
  },
  profileEditAvatar: {
    width: 80, height: 80, borderRadius: '50%', background: theme.gradient, color: '#fff',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 34, fontWeight: 700, marginBottom: 14, fontFamily: mono, boxShadow: theme.neonGlow,
  },
  profileEditAlias: { fontSize: 22, fontWeight: 700, marginBottom: 4, fontFamily: mono, color: theme.text },
  profileEditNote: { color: theme.textMuted, fontSize: 12, marginBottom: 24 },
  profileSection: { marginBottom: 18 },
  settingsCard: {
    background: theme.bgCard, border: `1px solid ${theme.border}`, borderRadius: 16,
    padding: 36, maxWidth: 500, display: 'flex', flexDirection: 'column',
  },
  settingRow: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '16px 0', borderBottom: `1px solid ${theme.border}`,
  },
  settingLabel: { fontWeight: 600, fontSize: 14, marginBottom: 3, color: theme.text },
  settingDesc: { color: theme.textMuted, fontSize: 12 },
  toggleOn: {
    width: 44, height: 24, borderRadius: 12, background: theme.gradient,
    cursor: 'pointer', position: 'relative', flexShrink: 0, boxShadow: theme.neonGlowSm,
  },
  toggleOff: {
    width: 44, height: 24, borderRadius: 12, background: theme.bgSurface,
    border: `1px solid ${theme.border}`, cursor: 'pointer', position: 'relative', flexShrink: 0,
  },
  toggleKnob: { width: 18, height: 18, borderRadius: '50%', background: '#fff', position: 'absolute', top: 3 },
  footer: {
    background: theme.bgCard, borderTop: `1px solid ${theme.border}`,
    padding: '12px 28px', fontSize: 11, color: theme.textMuted,
    display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 4,
    fontFamily: mono, letterSpacing: 0.5,
  },
  footerLink: { color: theme.textMuted, textDecoration: 'none' },
};
